FROM python:3.11.2

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose port for API (port 8000) and Streamlit (8501)
EXPOSE 8000
EXPOSE 8501

# Use Supervisor to run both services
RUN pip install supervisor

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["supervisord", "-n"]
